In [57]:
import polars as pl
import pandas as pd
import numpy as np
import plotly.express as px

pl.Config.set_tbl_hide_column_data_types(True)

GDP_Ann_df = pl.read_csv("API_Download_DS2_EN_csv_v2_179699.csv")
GDP_Ann_df

shape: (7, 28)
┌─────────────┬─────────┬─────────────┬─────────────┬───┬───────────┬───────────┬───────────┬──────┐
│ Country     ┆ Country ┆ Indicator   ┆ Indicator   ┆ … ┆ 2020      ┆ 2021      ┆ 2022      ┆      │
│ Name        ┆ Code    ┆ Name        ┆ Code        ┆   ┆           ┆           ┆           ┆      │
╞═════════════╪═════════╪═════════════╪═════════════╪═══╪═══════════╪═══════════╪═══════════╪══════╡
│ Brazil      ┆ BRA     ┆ GDP         ┆ NY.GDP.MKTP ┆ … ┆ 1.4761e12 ┆ 1.6706e12 ┆ 1.9519e12 ┆ null │
│             ┆         ┆ (current    ┆ .CD         ┆   ┆           ┆           ┆           ┆      │
│             ┆         ┆ US$)        ┆             ┆   ┆           ┆           ┆           ┆      │
│ Switzerland ┆ CHE     ┆ GDP         ┆ NY.GDP.MKTP ┆ … ┆ 7.5610e11 ┆ 8.4071e11 ┆ 8.5848e11 ┆ null │
│             ┆         ┆ (current    ┆ .CD         ┆   ┆           ┆           ┆           ┆      │
│             ┆         ┆ US$)        ┆             ┆   ┆           ┆           ┆           ┆      │
│ China       ┆ CHN     ┆ GDP         ┆ NY.GDP.MKTP ┆ … ┆ 1.4996e13 ┆ 1.8202e13 ┆ 1.8317e13 ┆ null │
│             ┆         ┆ (current    ┆ .CD         ┆   ┆           ┆           ┆           ┆      │
│             ┆         ┆ US$)        ┆             ┆   ┆           ┆           ┆           ┆      │
│ Germany     ┆ DEU     ┆ GDP         ┆ NY.GDP.MKTP ┆ … ┆ 3.9414e12 ┆ 4.3553e12 ┆ 4.2010e12 ┆ null │
│             ┆         ┆ (current    ┆ .CD         ┆   ┆           ┆           ┆           ┆      │
│             ┆         ┆ US$)        ┆             ┆   ┆           ┆           ┆           ┆      │
│ United      ┆ GBR     ┆ GDP         ┆ NY.GDP.MKTP ┆ … ┆ 2.7240e12 ┆ 3.1946e12 ┆ 3.1812e12 ┆ null │
│ Kingdom     ┆         ┆ (current    ┆ .CD         ┆   ┆           ┆           ┆           ┆      │
│             ┆         ┆ US$)        ┆             ┆   ┆           ┆           ┆           ┆      │
│ Japan       ┆ JPN     ┆ GDP         ┆ NY.GDP.MKTP ┆ … ┆ 5.1892e12 ┆ 5.2259e12 ┆ 4.4480e12 ┆ null │
│             ┆         ┆ (current    ┆ .CD         ┆   ┆           ┆           ┆           ┆      │
│             ┆         ┆ US$)        ┆             ┆   ┆           ┆           ┆           ┆      │
│ United      ┆ USA     ┆ GDP         ┆ NY.GDP.MKTP ┆ … ┆ 2.1375e13 ┆ 2.3726e13 ┆ 2.6055e13 ┆ null │
│ States      ┆         ┆ (current    ┆ .CD         ┆   ┆           ┆           ┆           ┆      │
│             ┆         ┆ US$)        ┆             ┆   ┆           ┆           ┆           ┆      │
└─────────────┴─────────┴─────────────┴─────────────┴───┴───────────┴───────────┴───────────┴──────┘

In [58]:
GDP_Ann_df = GDP_Ann_df.drop(["Country Code", "Indicator Name", "Indicator Code", ""])

year_columns = [str(year) for year in range(2000, 2023)]
GDP_Ann_df = GDP_Ann_df.with_columns([pl.col(col) / 1e9 for col in year_columns])
GDP_Ann_df = GDP_Ann_df.with_columns([pl.col(col).round() for col in year_columns])

GDP_Ann_df

shape: (7, 24)
┌────────────────┬─────────┬─────────┬─────────┬───┬─────────┬─────────┬─────────┬─────────┐
│ Country Name   ┆ 2000    ┆ 2001    ┆ 2002    ┆ … ┆ 2019    ┆ 2020    ┆ 2021    ┆ 2022    │
╞════════════════╪═════════╪═════════╪═════════╪═══╪═════════╪═════════╪═════════╪═════════╡
│ Brazil         ┆ 655.0   ┆ 560.0   ┆ 510.0   ┆ … ┆ 1873.0  ┆ 1476.0  ┆ 1671.0  ┆ 1952.0  │
│ Switzerland    ┆ 282.0   ┆ 290.0   ┆ 314.0   ┆ … ┆ 736.0   ┆ 756.0   ┆ 841.0   ┆ 858.0   │
│ China          ┆ 1224.0  ┆ 1355.0  ┆ 1490.0  ┆ … ┆ 14560.0 ┆ 14996.0 ┆ 18202.0 ┆ 18317.0 │
│ Germany        ┆ 1967.0  ┆ 1966.0  ┆ 2102.0  ┆ … ┆ 3960.0  ┆ 3941.0  ┆ 4355.0  ┆ 4201.0  │
│ United Kingdom ┆ 1672.0  ┆ 1656.0  ┆ 1791.0  ┆ … ┆ 2876.0  ┆ 2724.0  ┆ 3195.0  ┆ 3181.0  │
│ Japan          ┆ 5042.0  ┆ 4439.0  ┆ 4246.0  ┆ … ┆ 5246.0  ┆ 5189.0  ┆ 5226.0  ┆ 4448.0  │
│ United States  ┆ 10251.0 ┆ 10582.0 ┆ 10929.0 ┆ … ┆ 21540.0 ┆ 21375.0 ┆ 23726.0 ┆ 26055.0 │
└────────────────┴─────────┴─────────┴─────────┴───┴─────────┴─────────┴─────────┴─────────┘

In [59]:
GDP_Ann_df.null_count()

shape: (1, 24)
┌──────────────┬──────┬──────┬──────┬───┬──────┬──────┬──────┬──────┐
│ Country Name ┆ 2000 ┆ 2001 ┆ 2002 ┆ … ┆ 2019 ┆ 2020 ┆ 2021 ┆ 2022 │
╞══════════════╪══════╪══════╪══════╪═══╪══════╪══════╪══════╪══════╡
│ 0            ┆ 0    ┆ 0    ┆ 0    ┆ … ┆ 0    ┆ 0    ┆ 0    ┆ 0    │
└──────────────┴──────┴──────┴──────┴───┴──────┴──────┴──────┴──────┘

In [60]:
year_columns = [str(year) for year in range(2000, 2023)]



GDP_Ann_df_long = GDP_Ann_df.unpivot( index=["Country Name"],
    on=year_columns,
    variable_name="Year",
    value_name="GDP")

GDP_Ann_df_long = GDP_Ann_df_long.with_columns(pl.col("Year").cast(pl.Int32))
selected_countries = ["United States", "China", "Japan", "Germany", "United Kingdom"]
GDP_Ann_df_filtered = GDP_Ann_df_long.filter(pl.col("Country Name").is_in(selected_countries))

GDP_Ann_df_filtered

shape: (115, 3)
┌────────────────┬──────┬─────────┐
│ Country Name   ┆ Year ┆ GDP     │
╞════════════════╪══════╪═════════╡
│ China          ┆ 2000 ┆ 1224.0  │
│ Germany        ┆ 2000 ┆ 1967.0  │
│ United Kingdom ┆ 2000 ┆ 1672.0  │
│ Japan          ┆ 2000 ┆ 5042.0  │
│ United States  ┆ 2000 ┆ 10251.0 │
│ …              ┆ …    ┆ …       │
│ China          ┆ 2022 ┆ 18317.0 │
│ Germany        ┆ 2022 ┆ 4201.0  │
│ United Kingdom ┆ 2022 ┆ 3181.0  │
│ Japan          ┆ 2022 ┆ 4448.0  │
│ United States  ┆ 2022 ┆ 26055.0 │
└────────────────┴──────┴─────────┘

In [61]:
fig = px.line(GDP_Ann_df_filtered, x="Year", y="GDP", color="Country Name", markers=True, 
title="GDP over time (2000 - 2022)across Wealthy Countries", 
labels={"GDP": "GDP (Billions USD)", "Year": "Year", "Country Name": "Country"})

fig.show()